Курсовая/Controllers/CollectionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Курсовая.Domain;
using Курсовая.Domain.Entity;
using Курсовая.Models;

namespace Курсовая.Controllers
{
    public class CollectionController : Controller
    {
        DataManager _dataManager;
        AppDbContext _context;
        public CollectionController(DataManager dataManager, AppDbContext context) 
        {
            _dataManager = dataManager;
            _context = context;

        }
        [Authorize(Roles = "Admin")]  // Страница создания Коллекции
        public IActionResult Index()
        {
            var stamps = _context.Stamps.ToList();
            var collectors = _context.Collectors.ToList();

            ViewBag.Stamps = new SelectList(stamps, "Id", "Name");
            ViewBag.Collector = new SelectList(collectors, "Id", "FullName");
            ViewBag.StampDictionary = stamps.ToDictionary(s => s.Id, s => s.Name);

            return View(new Collection());
        }


        [HttpGet] // Страница просмотра Коллекций
        public async Task<IActionResult> GetAllColection()
        {
            var stamps = _context.Stamps.ToList();
            var collectors = _context.Collectors.ToList();
           /* ViewBag.Stamps = new SelectList(stamps, "Id", "Name");
            ViewBag.Collector = new SelectList(collectors, "Id", "FullName");*/

            var list = await _dataManager.collectionRepository.GetCollectionAllAsync();
            return View(list);
        }
        [Authorize(Roles = "Admin")] // Запрос на удаление
        [HttpPost]
        public async Task<IActionResult> Del(int id)
        {
            await _dataManager.collectionRepository.DeleteCollectionAsync(id);
            return RedirectToAction("GetAllColection");
        }

        [HttpPost] // Сохранение отредактированной сущьности коллекции
        public async Task<IActionResult> ModyfyColectionnn(Collection collection, List<int> stampIds)
        {
            collection.Stamps.Clear();
            var selectedStamps = await _context.Stamps.Where(s => stampIds.Contains(s.Id)).ToListAsync();
            foreach (var stamp in selectedStamps)
            {
                stamp.LastBy = DateTime.Now;
            }
            await _dataManager.collectionRepository.UpperStamp(collection, stampIds);
            return RedirectToAction("Index");
        }
        [HttpPost] // Первичное сохранение для новой Коллекции
        public async Task<IActionResult> SaveColectionnn(Collection collection, List<int> stampIds)
        {
            collection.Stamps.Clear();
            var selectedStamps = await _context.Stamps.Where(s => stampIds.Contains(s.Id)).ToListAsync();

            foreach (var stamp in selectedStamps) 
            {
                stamp.LastBy = DateTime.Now;
            }
            collection.Stamps = selectedStamps;
            await _dataManager.collectionRepository.SaveCollectionAsync(collection);

            return RedirectToAction("Index");
        }
        
        [HttpGet] //Для загрузки данных в представление для редактирования Коллекции
        public async Task<IActionResult> ModCollect(int id)
        {
            Collection? collection = await _dataManager.collectionRepository.GetCollectionByIdAsync(id);
            
            if (collection == null) return NotFound();

            ViewBag.Collector = new SelectList(_context.Collectors, "Id", "FullName"); // Нужно переделать что бы небыло связи с контекстом БД
            ViewBag.StampDictionary = _context.Stamps.ToDictionary(s => s.Id, s => s.Name); // Нужно переделать что бы небыло связи с контекстом БД

            return View(collection);
        }



        /*[HttpGet]
        public async Task<IActionResult> ColCol()
        {
            var setcollektors = await _dataManager.collectorRepository.GetCollectorAllAsync();
            return View(setcollektors);
        }*/









    }
}

Курсовая/Controllers/CollectorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Курсовая.Domain;
using Курсовая.Domain.Entity;

namespace Курсовая.Controllers
{
    public class CollectorController : Controller
    {
        DataManager _dataManager;
        public CollectorController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetCollectorAll()
        {
            var list = await _dataManager.collectorRepository.GetCollectorAllAsync();
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateCollector(Collector collector)
        {
            await _dataManager.collectorRepository.SaveCollectorAsync(collector);
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpDelete]  ///////////////////////////////////////////////////////////////////////////////////!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  [HttpPost]
        public async Task<IActionResult> DellCollector(int id)
        {
            await _dataManager.collectorRepository.DelCollectorAsync(id);
            return RedirectToAction("GetCollectorAll");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Redact(int id)
        {
            Collector? collector = await _dataManager.collectorRepository.GetCollectorByIdAsync(id);
            return View(collector);
        }

        [HttpGet]
        public async Task<IActionResult> GetCollectorByStampRare()
        {
            var a = await _dataManager.collectorRepository.GetCollectorByStampRare();
            return View(a);

        }
        [HttpGet]
        public async Task<IActionResult> GetRich()
        {
            var Model = await _dataManager.collectorRepository.GetRichCollector();
            return View(Model);

        }
        [HttpGet]
        public async Task<IActionResult> BigRare()
        {
            var a = await _dataManager.collectorRepository.GetBigRare();
            return View(a);
        }
        [HttpGet]
        public async Task<IActionResult> TopCollectors()
        {
            var collectors = await _dataManager.collectorRepository.SortColl();
            return View(collectors);
        }
        [HttpGet]
        public async Task<IActionResult> GetOldStamps()
        {
            var collectors = await _dataManager.collectorRepository.OldStamps();
            return View(collectors);
        }

    }
}

Курсовая/Controllers/StampController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Курсовая.Domain;
using Курсовая.Domain.Entity;

namespace Курсовая.Controllers
{
    public class StampController : Controller
    {
        DataManager dataManager;
        public StampController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }



        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Details(Stamp stamp) {
            await dataManager.stampRepository.SaveStampAsync(stamp);
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var a = await dataManager.stampRepository.GetStampAllAsync();
            return View(a);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task <IActionResult> Del(int id)
        {
            await dataManager.stampRepository.DelStamp(id);
            return RedirectToAction("Get");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task <IActionResult> Redact(int id)
        {
            Stamp? stamp = await dataManager.stampRepository.GetStampByIdAsync(id);
            return View(stamp);
        }

    }
}

Курсовая/Views/Shared/_FooterPartial.cshtml
<div class="container">
    &copy; 2025 - Курсовая - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

Курсовая/Views/Shared/_HeaderPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Курсовая</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Stamp" asp-action="Get">Stamp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Collector" asp-action="GetCollectorAll">Collector</a>
                </li>
            </ul>
        </div>


        @if (User.Identity?.IsAuthenticated == true)
        {
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    Stamp
                </button>
                <ul class="dropdown-menu">
                    <li><a asp-controller="Stamp" asp-action="Index" class="dropdown-item">Создание</a></li>
                    <li><a asp-controller="Stamp" asp-action="Get" class="dropdown-item">Просмотр</a></li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    Collector
                </button>
                <ul class="dropdown-menu">
                    <li><a asp-controller="Collector" asp-action="Index" class="dropdown-item">Создание</a></li>
                    <li><a asp-controller="Collector" asp-action="GetCollectorAll" class="dropdown-item">Просмотр</a></li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    Collection
                </button>
                <ul class="dropdown-menu">
                    <li><a asp-controller="Collection" asp-action="Index" class="dropdown-item">Создание</a></li>
                    <li><a asp-controller="Collection" asp-action="GetAllColection" class="dropdown-item">Просмотр</a></li>
                </ul>
            </div>
        }
        <a asp-action="Index" asp-controller="Account" class="profile-icon" title="Только Админ">
            <i class="fas fa-user-circle fa-lg"></i>
        </a>
    </div>
</nav>

Курсовая/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("_MetaPartial")
</head>
<body>
    <header>
        @await Html.PartialAsync("_HeaderPartial")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div> 

    <footer class="border-top footer text-muted">
        @await Html.PartialAsync("_FooterPartial")
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Курсовая/Views/Shared/_MetaPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - Курсовая</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/Курсовая.styles.css" asp-append-version="true" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />